services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - "8081:8080"   # Cambiado a 8081
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/containers:/var/lib/containers:ro
    networks:
      - monitoring-net
  prometheus:
    image: docker.io/prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    networks:
      - monitoring-net
    
    depends_on:
      - cadvisor

  grafana:
    image: docker.io/grafana/grafana-oss
    container_name: grafana
    ports:
      - "3001:3000"   # Cambiado a 3001
    networks:
      - monitoring-net
    depends_on:
      - prometheus
      
networks:
  monitoring-net:
    driver: bridge
